#pragma once

enum class EventType
{
	CLOSE_EVENT			= 0,
	RESIZE_EVENT		= 1,
	PAUSE_EVENT			= 2,
	KEY_EVENT			= 3,
	MOUSE_MORION_EVENT	= 4,
	MOUSE_BUTTON_EVENT	= 5, 
	CONTROLLER_EVENT	= 6,
	UNKNOWN_EVENT		= 7
};
